#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND "soerenbnoergaard"
#define DISTRHO_PLUGIN_NAME  "talchorus"
#define DISTRHO_PLUGIN_URI   "https://github.com/soerenbnoergaard/talchorus"

#define DISTRHO_PLUGIN_HAS_UI       0
#define DISTRHO_PLUGIN_IS_RT_SAFE   1
#define DISTRHO_PLUGIN_NUM_INPUTS   1
#define DISTRHO_PLUGIN_NUM_OUTPUTS  1
#define DISTRHO_PLUGIN_WANT_LATENCY 1

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
